services:
  # FastAPI 웹 서비스
  - type: web
    name: textmining-api
    env: python
    region: singapore  # 가장 가까운 리전 선택
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn fastapi_app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PYTHONPATH
        value: .
      - key: MAX_WORKERS
        value: 4
      - key: MEMORY_LIMIT_MB
        value: 512
    autoDeploy: true
    # AWS 버전 파일 제외
    excludeFiles:
      - fastapi_app_aws.py 